# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.alpha.example.com:
  peer1.alpha.example.com:
  peer0.beta.example.com:
  peer1.beta.example.com:

networks:
  bank:

services:

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - bank

  peer0.alpha.example.com:
    container_name: peer0.alpha.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.alpha.example.com
    networks:
      - bank

  peer1.alpha.example.com:
    container_name: peer1.alpha.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.alpha.example.com
    networks:
      - bank

  peer0.beta.example.com:
    container_name: peer0.beta.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.beta.example.com
    networks:
      - bank

  peer1.beta.example.com:
    container_name: peer1.beta.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.beta.example.com
    networks:
      - bank

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.alpha.example.com:7051
      - CORE_PEER_LOCALMSPID=AlphaMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/alpha.example.com/peers/peer0.alpha.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/alpha.example.com/peers/peer0.alpha.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/alpha.example.com/peers/peer0.alpha.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/alpha.example.com/users/Admin@alpha.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.alpha.example.com
      - peer1.alpha.example.com
      - peer0.beta.example.com
      - peer1.beta.example.com
    networks:
      - bank
